name: MoneySystem
main: me.daniel1385.moneysystem.MoneySystem
author: Daniel1385
version: ${project.version}
api-version: 1.21
depend: [floodgate, Vault]
commands:
  addmoney:
    permission: moneysystem.admin
  removemoney:
    permission: moneysystem.admin
  setmoney:
    permission: moneysystem.admin
  getmoney:
    permission: moneysystem.admin
  money:
    aliases: ["balance", "bal"]
  pay: {}
  bank: {}
  baltop: {}
  banktop: {}
